### ISSUE TITLE
老哥太够意思了，居然还在更新考研贴呢哈哈

### ISSUE THREAD

**Issue by 10cks** [guoJohnny/-837-#4]
我20年没考上，出来工作了都。总的来说还是感谢老哥的资料，很受用。估计以后有机会还会继续考，群解散了有些可惜。

**Comment by guoJohnny** [comment]
群解散也是没办法，学校出规定不允许在校生提供考研辅导，保险起见还是解散群了。

工作更能锻炼人，我当初也是这样，大四考研失败，出来工作了两年，在考的研。

不要灰心吧，工作也好，考研也好都是人生的一段经历罢了，好好过生活是最重要的。

**Comment by 10cks** [comment]
好的！
